version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.docker
    container_name: fastapi_app
    depends_on:
      - db

volumes:
  postgres_data: